FROM node:20 AS builder

ARG AFB_BASE_URL=/
ARG VITE_API_BASE_URL=http://localhost:8000/api/v1

ENV AFB_BASE_URL=${AFB_BASE_URL}
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

COPY src/attack_flow_builder /attack_flow_builder
WORKDIR /attack_flow_builder
RUN npm ci
RUN npm run build-only

FROM nginx:1.21-alpine
COPY --from=builder /attack_flow_builder/dist /usr/share/nginx/html
