import { writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { STIX_SOURCES } from "./sources.mjs";
import { fileURLToPath } from 'url';
import { fetchSourceData } from "./download_stix_source.mjs";
import { EXPORT_KEY } from "./source_utils.mjs";

/**
 * The enumeration file's directory.
 */
const ENUM_DIR  = `../src/assets/configuration/AttackFlowTemplates`;

/**
 * The domain prefix for tactics and techniques from sources without this information.
 */
const DOMAIN_PREFIXES = {
    MitreAtlas: "ATL",
    MitreF3: "F3"
}

/**
 * The ID prefix for tactics and techniques from sources without this information.
 */
const ID_PREFIXES = {
    MitreF3: "F3"
}

/**
 * The source name for objects generated by each enum file.
 */
const SOURCE_NAMES = {
    MitreAttack: "ATTACK",
    MitreAtlas: "ATLAS",
    MitreF3: "F3"
}

/**
 * JavaScript variable regex.
 */
const JS_VAR_REGEX = /^[a-z_$][a-z0-9_$]*$/i;

/**
 * Gets the display matrix label for a source object.
 * @param {Object} obj
 *  The source object.
 * @param {string} fileName
 *  The enum file's name.
 * @returns {string}
 *  The display matrix label.
 */
function getMatrix(obj, fileName) {
    return obj.domains ? obj.domains.map(
        o => o.substring(0, 3).toLocaleUpperCase()
    ).join(", ") : DOMAIN_PREFIXES[fileName];
}

/**
 * Gets the framework-scoped id for a source object.
 * @param {Object} obj
 *  The source object.
 * @param {string} fileName
 *  The enum file's name.
 * @returns {string}
 *  The framework-scoped id.
 */
function getSourceId(obj, fileName) {
    return ID_PREFIXES[fileName]
        ? `${ID_PREFIXES[fileName]}.${obj.id}`
        : obj.id;
}

/**
 * Adds a unique relationship to an array.
 * @param {Object[]} relationships
 *  The relationships.
 * @param {Set<string>} seen
 *  The already-seen relationship keys.
 * @param {Object} relationship
 *  The relationship.
 * @param {string[]} keyParts
 *  The relationship key parts.
 */
function addRelationship(relationships, seen, relationship, keyParts) {
    const key = keyParts.join("\0");
    if (seen.has(key)) {
        return;
    }
    relationships.push(relationship);
    seen.add(key);
}

/**
 * Tests if a source object should be exported.
 * @param {Object} obj
 *  The source object.
 * @returns {boolean}
 *  True if the object should be exported, false otherwise.
 */
function isActive(obj) {
    return !obj.deprecated;
}

/**
 * Adds source objects to an object record and registers their STIX ids.
 * @param {Object[]} objects
 *  The source objects.
 * @param {Record<string, Object>} records
 *  The object records to append to.
 * @param {Map<string, string>} sourceIdsByStixId
 *  The STIX id to external id map.
 * @param {string} fileName
 *  The enum file's name.
 */
function addSourceObjects(objects, records, sourceIdsByStixId, fileName) {
    for(const obj of objects) {
        const id = getSourceId(obj, fileName);
        const matrix = getMatrix(obj, fileName);
        records[id] = {
            id,
            name: obj.name,
            label: `[${matrix}] ${id} ${obj.name}`,
            type: obj.type,
            source: SOURCE_NAMES[fileName],
            domains: obj.domains,
            stixId: obj.stixId,
            url: obj.url
        };
        sourceIdsByStixId.set(obj.stixId, id);
    }
}

/**
 * Adds technique-to-defensive-object relationships.
 * @param {Object[]} objects
 *  The source objects.
 * @param {string} objectType
 *  The output relationship object type.
 * @param {string} stixRelationshipType
 *  The STIX relationship type to export.
 * @param {Object[]} relationships
 *  The relationships.
 * @param {Set<string>} seenRelationships
 *  The already-seen relationship keys.
 * @param {Map<string, string>} sourceIdsByStixId
 *  The STIX id to external id map.
 */
function addTechniqueDefensiveObjectRelationships(
    objects,
    objectType,
    stixRelationshipType,
    relationships,
    seenRelationships,
    sourceIdsByStixId
) {
    for(const obj of objects) {
        const objectId = sourceIdsByStixId.get(obj.stixId);
        if(!objectId) {
            continue;
        }
        for(const relation of obj.stixRelationships ?? []) {
            if(relation.relationshipType !== stixRelationshipType) {
                continue;
            }
            const techniqueId = sourceIdsByStixId.get(relation.targetRef);
            if(!techniqueId) {
                continue;
            }
            addRelationship(
                relationships,
                seenRelationships,
                {
                    techniqueId,
                    [`${objectType}Id`]: objectId
                },
                [techniqueId, objectId]
            );
        }
    }
}

/**
 * Sorts an object record by key.
 * @param {Record<string, Object>} record
 *  The object record.
 * @returns {Record<string, Object>}
 *  The sorted object record.
 */
function sortRecord(record) {
    return Object.fromEntries(
        Object.entries(record).sort(([a], [b]) => a.localeCompare(b))
    );
}

/**
 * Updates the specified enum file.
 * @param {string} fileName
 *  The enum file's name.
 */
export default async function updateApplicationSourceEnums(fileName) {
    const path = resolve(dirname(fileURLToPath(import.meta.url)), `${ ENUM_DIR }/${ fileName }.ts`);

    // Validate export key
    if(!JS_VAR_REGEX.test(EXPORT_KEY)) {
        throw new Error(`Export key '${ EXPORT_KEY }' is not a valid variable name.`);
    }

    // Collect data
    const types = await fetchSourceData(...STIX_SOURCES[fileName]);

    console.log(`→ Generating enumerations file...`);

    // Organize objects
    const tactics = {};
    const techniques = {};
    const mitigations = {};
    const detections = {};
    const tacticTechniques = [];
    const techniqueMitigations = [];
    const techniqueDetections = [];
    const sourceIdsByStixId = new Map();
    const seenTacticTechniques = new Set();
    const seenTechniqueMitigations = new Set();
    const seenTechniqueDetections = new Set();

    const activeTactics = types.get("tactic").filter(isActive);
    const activeTechniques = types.get("technique").filter(isActive);
    const activeMitigations = (types.get("mitigation") ?? []).filter(isActive);
    const activeDetections = (types.get("detection") ?? []).filter(isActive);

    addSourceObjects(activeTactics, tactics, sourceIdsByStixId, fileName);
    addSourceObjects(activeTechniques, techniques, sourceIdsByStixId, fileName);
    addSourceObjects(activeMitigations, mitigations, sourceIdsByStixId, fileName);
    addSourceObjects(activeDetections, detections, sourceIdsByStixId, fileName);

    // Organize tactic-to-technique relationships
    for(const tactic of activeTactics) {
        const tacticId = sourceIdsByStixId.get(tactic.stixId);
        if(!tacticId) {
            continue;
        }
        for(const technique of tactic.techniques ?? []) {
            const techniqueId = sourceIdsByStixId.get(technique.stixId);
            if(!techniqueId) {
                continue;
            }
            addRelationship(
                tacticTechniques,
                seenTacticTechniques,
                { tacticId, techniqueId },
                [tacticId, techniqueId]
            );
        }
    }

    // Organize technique-to-defensive-object relationships
    addTechniqueDefensiveObjectRelationships(
        activeMitigations,
        "mitigation",
        "mitigates",
        techniqueMitigations,
        seenTechniqueMitigations,
        sourceIdsByStixId
    );
    addTechniqueDefensiveObjectRelationships(
        activeDetections,
        "detection",
        "detects",
        techniqueDetections,
        seenTechniqueDetections,
        sourceIdsByStixId
    );

    // Generate enums file
    let file = "";
    file += `export const ${ EXPORT_KEY } = `;
    const relationships = {
        tacticTechniques,
        techniqueMitigations,
        techniqueDetections
    };
    file += JSON.stringify({
        tactics: sortRecord(tactics),
        techniques: sortRecord(techniques),
        mitigations: sortRecord(mitigations),
        detections: sortRecord(detections),
        relationships
    }, null, 4);
    file += `;\n\nexport default ${ EXPORT_KEY };\n`
    writeFileSync(path, file);

    // Done
    console.log("\nSource enumerations updated successfully.\n");

}
