export const GroupingContextOv : [string, string][] = [
        ['suspicious-activity', 'Suspicious Activity'],
        ['malware-analysis', 'Malware Analysis'],
        ['unspecified', 'Unspecified'],
];
export const ReportTypeOv : [string, string][] = [
        ['threat-report', 'Threat Report'],
        ['attack-pattern', 'Attack Pattern'],
        ['campaign', 'Campaign'],
        ['identity', 'Identity'],
        ['indicator', 'Indicator'],
        ['malware', 'Malware'],
        ['observed-data', 'Observed Data'],
        ['threat-actor', 'Threat Actor'],
        ['tool', 'Tool'],
        ['vulnerability', 'Vulnerability'],
];
export const RegionOv : [string, string][] = [
        ['africa', 'Africa'],
        ['eastern-africa', 'Eastern Africa'],
        ['middle-africa', 'Middle Africa'],
        ['northern-africa', 'Northern Africa'],
        ['southern-africa', 'Southern Africa'],
        ['western-africa', 'Western Africa'],
        ['americas', 'Americas'],
        ['latin-america-caribbean', 'Latin America Caribbean'],
        ['south-america', 'South America'],
        ['caribbean', 'Caribbean'],
        ['central-america northern-america', 'Central America Northern America'],
        ['asia', 'Asia'],
        ['central-asia', 'Central Asia'],
        ['eastern-asia', 'Eastern Asia'],
        ['southern-asia', 'Southern Asia'],
        ['western-asia', 'Western Asia'],
        ['europe eastern-europe', 'Europe Eastern Europe'],
        ['northern-europe', 'Northern Europe'],
        ['southern-europe', 'Southern Europe'],
        ['western-europe', 'Western Europe'],
        ['oceania', 'Oceania'],
        ['australia-new-zealand', 'Australia New Zealand'],
        ['melanesia', 'Melanesia'],
        ['micronesia', 'Micronesia'],
        ['polynesia', 'Polynesia'],
        ['antarctica', 'Antarctica'],
];
export const MalwareTypeOv : [string, string][] = [
        ['adware', 'Adware'],
        ['backdoor', 'Backdoor'],
        ['bot', 'Bot'],
        ['bootkit', 'Bootkit'],
        ['ddos', 'Ddos'],
        ['downloader', 'Downloader'],
        ['dropper', 'Dropper'],
        ['exploit-kit', 'Exploit Kit'],
        ['keylogger', 'Keylogger'],
        ['ransomware', 'Ransomware'],
        ['remote-access-trojan', 'Remote Access Trojan'],
        ['resource-exploitation', 'Resource Exploitation'],
        ['rogue-security-software', 'Rogue Security Software'],
        ['rootkit', 'Rootkit'],
        ['screen-capture', 'Screen Capture'],
        ['spyware', 'Spyware'],
        ['trojan', 'Trojan'],
        ['unknown', 'Unknown'],
        ['virus', 'Virus'],
        ['webshell', 'Webshell'],
        ['wiper', 'Wiper'],
        ['worm', 'Worm'],
];
export const ImplementationLanguageOv : [string, string][] = [
        ['applescript', 'Applescript'],
        ['bash', 'Bash'],
        ['c', 'C'],
        ['c++', 'C++'],
        ['c#', 'C#'],
        ['go', 'Go'],
        ['java', 'Java'],
        ['javascript', 'Javascript'],
        ['lua', 'Lua'],
        ['objective-c', 'Objective C'],
        ['perl', 'Perl'],
        ['php', 'Php'],
        ['powershell', 'Powershell'],
        ['python', 'Python'],
        ['ruby', 'Ruby'],
        ['scala', 'Scala'],
        ['swift', 'Swift'],
        ['typescript', 'Typescript'],
        ['visual-basic', 'Visual Basic'],
        ['x86-32', 'X86 32'],
        ['x86-64', 'X86 64'],
];
export const MalwareCapabilitiesOv : [string, string][] = [
        ['accesses-remote-machines', 'Accesses Remote Machines'],
        ['anti-debugging', 'Anti Debugging'],
        ['anti-disassembly', 'Anti Disassembly'],
        ['anti-emulation', 'Anti Emulation'],
        ['anti-memory-forensics', 'Anti Memory Forensics'],
        ['anti-sandbox', 'Anti Sandbox'],
        ['anti-vm', 'Anti Vm'],
        ['captures-input-peripherals', 'Captures Input Peripherals'],
        ['captures-output-peripherals', 'Captures Output Peripherals'],
        ['captures-system-state-data', 'Captures System State Data'],
        ['cleans-traces-of-infection', 'Cleans Traces Of Infection'],
        ['commits-fraud', 'Commits Fraud'],
        ['communicates-with-c2', 'Communicates With C2'],
        ['compromises-data-availability', 'Compromises Data Availability'],
        ['compromises-data-integrity', 'Compromises Data Integrity'],
        ['compromises-system-availability', 'Compromises System Availability'],
        ['controls-local-machine', 'Controls Local Machine'],
        ['degrades-security-software', 'Degrades Security Software'],
        ['degrades-system-updates', 'Degrades System Updates'],
        ['determines-c2-server', 'Determines C2 Server'],
        ['emails-spam', 'Emails Spam'],
        ['escalates-privileges', 'Escalates Privileges'],
        ['evades-av', 'Evades Av'],
        ['exfiltrates-data', 'Exfiltrates Data'],
        ['fingerprints-host', 'Fingerprints Host'],
        ['hides-artifacts', 'Hides Artifacts'],
        ['hides-executing-code', 'Hides Executing Code'],
        ['infects-files', 'Infects Files'],
        ['infects-remote-machines', 'Infects Remote Machines'],
        ['installs-other-components', 'Installs Other Components'],
        ['persists-after-system-reboot', 'Persists After System Reboot'],
        ['prevents-artifact-access', 'Prevents Artifact Access'],
        ['prevents-artifact-deletion', 'Prevents Artifact Deletion'],
        ['probes-network-environment', 'Probes Network Environment'],
        ['self-modifies', 'Self Modifies'],
        ['steals-authentication-credentials', 'Steals Authentication Credentials'],
        ['violates-system-operational-integrity', 'Violates System Operational Integrity'],
];
export const ProcessorArchitectureOv : [string, string][] = [
        ['alpha', 'Alpha'],
        ['arm', 'Arm'],
        ['ia-64', 'Ia 64'],
        ['mips', 'Mips'],
        ['powerpc', 'Powerpc'],
        ['sparc', 'Sparc'],
        ['x86', 'X86'],
        ['x86-64', 'X86 64'],
];
export const ToolTypeOv : [string, string][] = [
        ['denial-of-service', 'Denial Of Service'],
        ['exploitation', 'Exploitation'],
        ['information-gathering', 'Information Gathering'],
        ['network-capture', 'Network Capture'],
        ['credential-exploitation', 'Credential Exploitation'],
        ['remote-access', 'Remote Access'],
        ['vulnerability-scanning', 'Vulnerability Scanning'],
        ['unknown', 'Unknown'],
];
export const ThreatActorTypeOv : [string, string][] = [
        ['activist', 'Activist'],
        ['competitor', 'Competitor'],
        ['crime-syndicate', 'Crime Syndicate'],
        ['criminal', 'Criminal'],
        ['hacker', 'Hacker'],
        ['insider-accidental', 'Insider Accidental'],
        ['insider-disgruntled', 'Insider Disgruntled'],
        ['nation-state', 'Nation State'],
        ['sensationalist', 'Sensationalist'],
        ['spy', 'Spy'],
        ['terrorist', 'Terrorist'],
        ['unknown', 'Unknown'],
];
export const ThreatActorRoleOv : [string, string][] = [
        ['agent', 'Agent'],
        ['director', 'Director'],
        ['independent', 'Independent'],
        ['sponsor', 'Sponsor'],
        ['infrastructure-operator', 'Infrastructure Operator'],
        ['infrastructure-architect', 'Infrastructure Architect'],
        ['malware-author', 'Malware Author'],
];
export const ThreatActorSophisticationOv : [string, string][] = [
        ['none', 'None'],
        ['minimal', 'Minimal'],
        ['intermediate', 'Intermediate'],
        ['advanced', 'Advanced'],
        ['strategic', 'Strategic'],
        ['expert', 'Expert'],
        ['innovator', 'Innovator'],
];
export const AttackResourceLevelOv : [string, string][] = [
        ['individual', 'Individual'],
        ['club', 'Club'],
        ['contest', 'Contest'],
        ['team', 'Team'],
        ['organization', 'Organization'],
        ['government', 'Government'],
];
export const AttackMotivationOv : [string, string][] = [
        ['accidental', 'Accidental'],
        ['coercion', 'Coercion'],
        ['dominance', 'Dominance'],
        ['ideology', 'Ideology'],
        ['notoriety', 'Notoriety'],
        ['organizational-gain', 'Organizational Gain'],
        ['personal-gain', 'Personal Gain'],
        ['personal-satisfaction', 'Personal Satisfaction'],
        ['revenge', 'Revenge'],
        ['unpredictable', 'Unpredictable'],
];
export const MalwareResultOv : [string, string][] = [
        ['malicious', 'Malicious'],
        ['suspicious', 'Suspicious'],
        ['benign', 'Benign'],
        ['unknown', 'Unknown'],
];
export const IdentityClassOv : [string, string][] = [
        ['individual', 'Individual'],
        ['group', 'Group'],
        ['system', 'System'],
        ['organization', 'Organization'],
        ['class', 'Class'],
        ['unknown', 'Unknown'],
];
export const IndustrySectorOv : [string, string][] = [
        ['agriculture', 'Agriculture'],
        ['aerospace', 'Aerospace'],
        ['automotive', 'Automotive'],
        ['chemical', 'Chemical'],
        ['commercial', 'Commercial'],
        ['communications', 'Communications'],
        ['construction', 'Construction'],
        ['defense', 'Defense'],
        ['education', 'Education'],
        ['energy', 'Energy'],
        ['engineering', 'Engineering'],
        ['entertainment', 'Entertainment'],
        ['financial-services', 'Financial Services'],
        ['government', 'Government'],
        ['emergency-services', 'Emergency Services'],
        ['government-local', 'Government Local'],
        ['government-national', 'Government National'],
        ['government-public-services', 'Government Public Services'],
        ['government-regional', 'Government Regional'],
        ['healthcare', 'Healthcare'],
        ['hospitality-leisure', 'Hospitality Leisure'],
        ['infrastructure', 'Infrastructure'],
        ['dams', 'Dams'],
        ['nuclear', 'Nuclear'],
        ['water', 'Water'],
        ['insurance', 'Insurance'],
        ['manufacturing', 'Manufacturing'],
        ['mining', 'Mining'],
        ['non-profit', 'Non Profit'],
        ['pharmaceuticals', 'Pharmaceuticals'],
        ['retail', 'Retail'],
        ['technology', 'Technology'],
        ['telecommunications', 'Telecommunications'],
        ['transportation', 'Transportation'],
        ['utilities', 'Utilities'],
];
export const IndicatorTypeOv : [string, string][] = [
        ['anomalous-activity', 'Anomalous Activity'],
        ['anonymization', 'Anonymization'],
        ['benign', 'Benign'],
        ['compromised', 'Compromised'],
        ['malicious-activity', 'Malicious Activity'],
        ['attribution', 'Attribution'],
        ['unknown', 'Unknown'],
];
export const PatternTypeOv : [string, string][] = [
        ['stix', 'Stix'],
        ['pcre', 'Pcre'],
        ['sigma', 'Sigma'],
        ['snort', 'Snort'],
        ['suricata', 'Suricata'],
        ['yara', 'Yara'],
];
export const InfrastructureTypeOv : [string, string][] = [
        ['amplification', 'Amplification'],
        ['anonymization', 'Anonymization'],
        ['botnet', 'Botnet'],
        ['command-and-control', 'Command And Control'],
        ['exfiltration', 'Exfiltration'],
        ['hosting-malware', 'Hosting Malware'],
        ['hosting-target-lists', 'Hosting Target Lists'],
        ['phishing', 'Phishing'],
        ['reconnaissance', 'Reconnaissance'],
        ['staging', 'Staging'],
        ['unknown', 'Unknown'],
];
export const AccountTypeOv : [string, string][] = [
        ['unix', 'Unix'],
        ['windows local', 'Windows Local'],
        ['windows domain', 'Windows Domain'],
        ['ldap', 'Ldap'],
        ['tacacs', 'Tacacs'],
        ['radius', 'Radius'],
        ['nis', 'Nis'],
        ['openid', 'Openid'],
        ['facebook', 'Facebook'],
        ['skype', 'Skype'],
        ['twitter', 'Twitter'],
        ['kavi', 'Kavi'],
];
export const WindowsPebinaryTypeOv : [string, string][] = [
        ['exe', 'Exe'],
        ['dll', 'Dll'],
        ['sys', 'Sys'],
];
